"""
Resort seed data — 20 Epic + 25 Ikon North American resorts.

NOTE: liftie_id values are slugs used by liftie.info/api/resort/{slug}.
NOTE: onthesnow_slug values are URL path segments from onthesnow.com.
Verify both before going to production.
"""
from sqlalchemy.orm import Session
from app.models.resort import Resort

RESORTS: list[dict] = [
    # ── EPIC PASS (20 resorts) ────────────────────────────────────────────
    {
        "id": "vail", "name": "Vail", "pass_type": "epic",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.6061, "longitude": -106.3550,
        "summit_elevation_ft": 11570, "vertical_drop_ft": 3450,
        "website": "https://www.vail.com", "timezone": "America/Denver",
        "liftie_id": "vail", "onthesnow_slug": "colorado/vail-ski-resort",
    },
    {
        "id": "beaver-creek", "name": "Beaver Creek", "pass_type": "epic",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.6042, "longitude": -106.5165,
        "summit_elevation_ft": 11440, "vertical_drop_ft": 4040,
        "website": "https://www.beavercreek.com", "timezone": "America/Denver",
        "liftie_id": "beaver-creek", "onthesnow_slug": "colorado/beaver-creek-ski-resort",
    },
    {
        "id": "breckenridge", "name": "Breckenridge", "pass_type": "epic",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.4817, "longitude": -106.0384,
        "summit_elevation_ft": 12998, "vertical_drop_ft": 3398,
        "website": "https://www.breckenridge.com", "timezone": "America/Denver",
        "liftie_id": "breckenridge", "onthesnow_slug": "colorado/breckenridge-ski-resort",
    },
    {
        "id": "keystone", "name": "Keystone", "pass_type": "epic",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.6086, "longitude": -105.9537,
        "summit_elevation_ft": 12408, "vertical_drop_ft": 2900,
        "website": "https://www.keystoneresort.com", "timezone": "America/Denver",
        "liftie_id": "keystone", "onthesnow_slug": "colorado/keystone-ski-resort",
    },
    {
        "id": "park-city", "name": "Park City", "pass_type": "epic",
        "region": "Utah", "state": "UT", "country": "US",
        "latitude": 40.6514, "longitude": -111.5080,
        "summit_elevation_ft": 10026, "vertical_drop_ft": 3226,
        "website": "https://www.parkcitymountain.com", "timezone": "America/Denver",
        "liftie_id": "park-city", "onthesnow_slug": "utah/park-city-mountain-resort",
    },
    {
        "id": "crested-butte", "name": "Crested Butte", "pass_type": "epic",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 38.8981, "longitude": -106.9650,
        "summit_elevation_ft": 12162, "vertical_drop_ft": 2775,
        "website": "https://www.skicb.com", "timezone": "America/Denver",
        "liftie_id": "crested-butte", "onthesnow_slug": "colorado/crested-butte-mountain-resort",
    },
    {
        "id": "stevens-pass", "name": "Stevens Pass", "pass_type": "epic",
        "region": "Pacific Northwest", "state": "WA", "country": "US",
        "latitude": 47.7448, "longitude": -121.0900,
        "summit_elevation_ft": 5845, "vertical_drop_ft": 1800,
        "website": "https://www.stevenspass.com", "timezone": "America/Los_Angeles",
        "liftie_id": "stevens-pass", "onthesnow_slug": "washington/stevens-pass-ski-area",
    },
    {
        "id": "stowe", "name": "Stowe", "pass_type": "epic",
        "region": "Northeast", "state": "VT", "country": "US",
        "latitude": 44.5303, "longitude": -72.7814,
        "summit_elevation_ft": 4393, "vertical_drop_ft": 2360,
        "website": "https://www.stowe.com", "timezone": "America/New_York",
        "liftie_id": "stowe", "onthesnow_slug": "vermont/stowe-mountain-resort",
    },
    {
        "id": "whistler-blackcomb", "name": "Whistler Blackcomb", "pass_type": "epic",
        "region": "British Columbia", "state": "BC", "country": "CA",
        "latitude": 50.1163, "longitude": -122.9574,
        "summit_elevation_ft": 7494, "vertical_drop_ft": 5280,
        "website": "https://www.whistlerblackcomb.com", "timezone": "America/Vancouver",
        "liftie_id": "whistler-blackcomb", "onthesnow_slug": "british-columbia/whistler-blackcomb",
    },
    {
        "id": "afton-alps", "name": "Afton Alps", "pass_type": "epic",
        "region": "Midwest", "state": "MN", "country": "US",
        "latitude": 44.8622, "longitude": -92.7917,
        "summit_elevation_ft": 1165, "vertical_drop_ft": 350,
        "website": "https://www.aftonalps.com", "timezone": "America/Chicago",
        "liftie_id": "afton-alps", "onthesnow_slug": "minnesota/afton-alps",
    },
    {
        "id": "mount-snow", "name": "Mount Snow", "pass_type": "epic",
        "region": "Northeast", "state": "VT", "country": "US",
        "latitude": 42.9595, "longitude": -72.9223,
        "summit_elevation_ft": 3600, "vertical_drop_ft": 1700,
        "website": "https://www.mountsnow.com", "timezone": "America/New_York",
        "liftie_id": "mount-snow", "onthesnow_slug": "vermont/mount-snow",
    },
    {
        "id": "wildcat", "name": "Wildcat Mountain", "pass_type": "epic",
        "region": "Northeast", "state": "NH", "country": "US",
        "latitude": 44.2620, "longitude": -71.2387,
        "summit_elevation_ft": 4062, "vertical_drop_ft": 2112,
        "website": "https://www.skiwildcat.com", "timezone": "America/New_York",
        "liftie_id": "wildcat", "onthesnow_slug": "new-hampshire/wildcat-mountain",
    },
    {
        "id": "attitash", "name": "Attitash", "pass_type": "epic",
        "region": "Northeast", "state": "NH", "country": "US",
        "latitude": 44.0796, "longitude": -71.2293,
        "summit_elevation_ft": 2350, "vertical_drop_ft": 1750,
        "website": "https://www.attitash.com", "timezone": "America/New_York",
        "liftie_id": "attitash", "onthesnow_slug": "new-hampshire/attitash-mountain-resort",
    },
    {
        "id": "hunter-mountain", "name": "Hunter Mountain", "pass_type": "epic",
        "region": "Northeast", "state": "NY", "country": "US",
        "latitude": 42.1810, "longitude": -74.2268,
        "summit_elevation_ft": 3200, "vertical_drop_ft": 1600,
        "website": "https://www.huntermtn.com", "timezone": "America/New_York",
        "liftie_id": "hunter-mountain", "onthesnow_slug": "new-york/hunter-mountain",
    },
    {
        "id": "jack-frost", "name": "Jack Frost", "pass_type": "epic",
        "region": "Northeast", "state": "PA", "country": "US",
        "latitude": 41.0879, "longitude": -75.7038,
        "summit_elevation_ft": 2000, "vertical_drop_ft": 600,
        "website": "https://www.jackfrostbigboulder.com", "timezone": "America/New_York",
        "liftie_id": "jack-frost", "onthesnow_slug": "pennsylvania/jack-frost",
    },
    {
        "id": "big-boulder", "name": "Big Boulder", "pass_type": "epic",
        "region": "Northeast", "state": "PA", "country": "US",
        "latitude": 41.0524, "longitude": -75.5976,
        "summit_elevation_ft": 2175, "vertical_drop_ft": 475,
        "website": "https://www.jackfrostbigboulder.com", "timezone": "America/New_York",
        "liftie_id": "big-boulder", "onthesnow_slug": "pennsylvania/big-boulder",
    },
    {
        "id": "liberty-mountain", "name": "Liberty Mountain", "pass_type": "epic",
        "region": "Mid-Atlantic", "state": "PA", "country": "US",
        "latitude": 39.8198, "longitude": -77.3597,
        "summit_elevation_ft": 1560, "vertical_drop_ft": 620,
        "website": "https://www.libertymountainresort.com", "timezone": "America/New_York",
        "liftie_id": "liberty-mountain", "onthesnow_slug": "pennsylvania/liberty-mountain-resort",
    },
    {
        "id": "roundtop", "name": "Roundtop Mountain", "pass_type": "epic",
        "region": "Mid-Atlantic", "state": "PA", "country": "US",
        "latitude": 40.1162, "longitude": -76.8318,
        "summit_elevation_ft": 1400, "vertical_drop_ft": 600,
        "website": "https://www.skiroundtop.com", "timezone": "America/New_York",
        "liftie_id": "roundtop", "onthesnow_slug": "pennsylvania/roundtop-mountain-resort",
    },
    {
        "id": "whitetail", "name": "Whitetail Resort", "pass_type": "epic",
        "region": "Mid-Atlantic", "state": "PA", "country": "US",
        "latitude": 39.9565, "longitude": -77.9107,
        "summit_elevation_ft": 2335, "vertical_drop_ft": 935,
        "website": "https://www.skiwhitetail.com", "timezone": "America/New_York",
        "liftie_id": "whitetail", "onthesnow_slug": "pennsylvania/whitetail-resort",
    },
    {
        "id": "wilmot-mountain", "name": "Wilmot Mountain", "pass_type": "epic",
        "region": "Midwest", "state": "WI", "country": "US",
        "latitude": 42.5272, "longitude": -88.2067,
        "summit_elevation_ft": 1150, "vertical_drop_ft": 230,
        "website": "https://www.wilmotmountain.com", "timezone": "America/Chicago",
        "liftie_id": "wilmot-mountain", "onthesnow_slug": "wisconsin/wilmot-mountain",
    },
    # ── IKON PASS (25 resorts) ────────────────────────────────────────────
    {
        "id": "aspen-snowmass", "name": "Aspen Snowmass", "pass_type": "ikon",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.2084, "longitude": -106.9498,
        "summit_elevation_ft": 12510, "vertical_drop_ft": 4406,
        "website": "https://www.aspensnowmass.com", "timezone": "America/Denver",
        "liftie_id": "aspen-snowmass", "onthesnow_slug": "colorado/aspen-snowmass",
    },
    {
        "id": "mammoth", "name": "Mammoth Mountain", "pass_type": "ikon",
        "region": "California", "state": "CA", "country": "US",
        "latitude": 37.6308, "longitude": -119.0326,
        "summit_elevation_ft": 11053, "vertical_drop_ft": 3100,
        "website": "https://www.mammothmountain.com", "timezone": "America/Los_Angeles",
        "liftie_id": "mammoth", "onthesnow_slug": "california/mammoth-mountain-ski-area",
    },
    {
        "id": "jackson-hole", "name": "Jackson Hole", "pass_type": "ikon",
        "region": "Wyoming", "state": "WY", "country": "US",
        "latitude": 43.5875, "longitude": -110.8279,
        "summit_elevation_ft": 10450, "vertical_drop_ft": 4139,
        "website": "https://www.jacksonhole.com", "timezone": "America/Denver",
        "liftie_id": "jackson-hole", "onthesnow_slug": "wyoming/jackson-hole-mountain-resort",
    },
    {
        "id": "big-sky", "name": "Big Sky", "pass_type": "ikon",
        "region": "Montana", "state": "MT", "country": "US",
        "latitude": 45.2860, "longitude": -111.4015,
        "summit_elevation_ft": 11166, "vertical_drop_ft": 4350,
        "website": "https://www.bigskyresort.com", "timezone": "America/Denver",
        "liftie_id": "big-sky", "onthesnow_slug": "montana/big-sky-resort",
    },
    {
        "id": "steamboat", "name": "Steamboat", "pass_type": "ikon",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 40.4572, "longitude": -106.8045,
        "summit_elevation_ft": 10568, "vertical_drop_ft": 3668,
        "website": "https://www.steamboat.com", "timezone": "America/Denver",
        "liftie_id": "steamboat", "onthesnow_slug": "colorado/steamboat-ski-resort",
    },
    {
        "id": "winter-park", "name": "Winter Park", "pass_type": "ikon",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.8868, "longitude": -105.7625,
        "summit_elevation_ft": 12060, "vertical_drop_ft": 3060,
        "website": "https://www.winterparkresort.com", "timezone": "America/Denver",
        "liftie_id": "winter-park", "onthesnow_slug": "colorado/winter-park-resort",
    },
    {
        "id": "palisades-tahoe", "name": "Palisades Tahoe", "pass_type": "ikon",
        "region": "California", "state": "CA", "country": "US",
        "latitude": 39.1970, "longitude": -120.2358,
        "summit_elevation_ft": 9050, "vertical_drop_ft": 2600,
        "website": "https://www.palisadestahoe.com", "timezone": "America/Los_Angeles",
        "liftie_id": "palisades-tahoe", "onthesnow_slug": "california/palisades-tahoe",
    },
    {
        "id": "alta", "name": "Alta", "pass_type": "ikon",
        "region": "Utah", "state": "UT", "country": "US",
        "latitude": 40.5882, "longitude": -111.6373,
        "summit_elevation_ft": 10550, "vertical_drop_ft": 2538,
        "website": "https://www.alta.com", "timezone": "America/Denver",
        "liftie_id": "alta", "onthesnow_slug": "utah/alta-ski-area",
    },
    {
        "id": "snowbird", "name": "Snowbird", "pass_type": "ikon",
        "region": "Utah", "state": "UT", "country": "US",
        "latitude": 40.5830, "longitude": -111.6558,
        "summit_elevation_ft": 11000, "vertical_drop_ft": 3240,
        "website": "https://www.snowbird.com", "timezone": "America/Denver",
        "liftie_id": "snowbird", "onthesnow_slug": "utah/snowbird",
    },
    {
        "id": "copper-mountain", "name": "Copper Mountain", "pass_type": "ikon",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.4997, "longitude": -106.1497,
        "summit_elevation_ft": 12313, "vertical_drop_ft": 2601,
        "website": "https://www.coppercolorado.com", "timezone": "America/Denver",
        "liftie_id": "copper-mountain", "onthesnow_slug": "colorado/copper-mountain-resort",
    },
    {
        "id": "arapahoe-basin", "name": "Arapahoe Basin", "pass_type": "ikon",
        "region": "Colorado", "state": "CO", "country": "US",
        "latitude": 39.6426, "longitude": -105.8716,
        "summit_elevation_ft": 13050, "vertical_drop_ft": 2530,
        "website": "https://www.arapahoebasin.com", "timezone": "America/Denver",
        "liftie_id": "arapahoe-basin", "onthesnow_slug": "colorado/arapahoe-basin-ski-area",
    },
    {
        "id": "taos", "name": "Taos Ski Valley", "pass_type": "ikon",
        "region": "New Mexico", "state": "NM", "country": "US",
        "latitude": 36.5952, "longitude": -105.4475,
        "summit_elevation_ft": 12481, "vertical_drop_ft": 2612,
        "website": "https://www.skitaos.com", "timezone": "America/Denver",
        "liftie_id": "taos", "onthesnow_slug": "new-mexico/taos-ski-valley",
    },
    {
        "id": "stratton", "name": "Stratton Mountain", "pass_type": "ikon",
        "region": "Northeast", "state": "VT", "country": "US",
        "latitude": 43.1121, "longitude": -72.9076,
        "summit_elevation_ft": 3875, "vertical_drop_ft": 2003,
        "website": "https://www.stratton.com", "timezone": "America/New_York",
        "liftie_id": "stratton", "onthesnow_slug": "vermont/stratton-mountain-resort",
    },
    {
        "id": "sugarbush", "name": "Sugarbush", "pass_type": "ikon",
        "region": "Northeast", "state": "VT", "country": "US",
        "latitude": 44.1370, "longitude": -72.8986,
        "summit_elevation_ft": 4083, "vertical_drop_ft": 2600,
        "website": "https://www.sugarbush.com", "timezone": "America/New_York",
        "liftie_id": "sugarbush", "onthesnow_slug": "vermont/sugarbush-resort",
    },
    {
        "id": "loon-mountain", "name": "Loon Mountain", "pass_type": "ikon",
        "region": "Northeast", "state": "NH", "country": "US",
        "latitude": 44.0341, "longitude": -71.6237,
        "summit_elevation_ft": 3050, "vertical_drop_ft": 2100,
        "website": "https://www.loonmtn.com", "timezone": "America/New_York",
        "liftie_id": "loon-mountain", "onthesnow_slug": "new-hampshire/loon-mountain-resort",
    },
    {
        "id": "killington", "name": "Killington", "pass_type": "ikon",
        "region": "Northeast", "state": "VT", "country": "US",
        "latitude": 43.6726, "longitude": -72.7782,
        "summit_elevation_ft": 4241, "vertical_drop_ft": 3050,
        "website": "https://www.killington.com", "timezone": "America/New_York",
        "liftie_id": "killington", "onthesnow_slug": "vermont/killington-resort",
    },
    {
        "id": "sunday-river", "name": "Sunday River", "pass_type": "ikon",
        "region": "Northeast", "state": "ME", "country": "US",
        "latitude": 44.4696, "longitude": -70.8563,
        "summit_elevation_ft": 3140, "vertical_drop_ft": 2340,
        "website": "https://www.sundayriver.com", "timezone": "America/New_York",
        "liftie_id": "sunday-river", "onthesnow_slug": "maine/sunday-river",
    },
    {
        "id": "sugarloaf", "name": "Sugarloaf", "pass_type": "ikon",
        "region": "Northeast", "state": "ME", "country": "US",
        "latitude": 45.0311, "longitude": -70.3136,
        "summit_elevation_ft": 4237, "vertical_drop_ft": 2820,
        "website": "https://www.sugarloaf.com", "timezone": "America/New_York",
        "liftie_id": "sugarloaf", "onthesnow_slug": "maine/sugarloaf",
    },
    {
        "id": "crystal-mountain", "name": "Crystal Mountain", "pass_type": "ikon",
        "region": "Pacific Northwest", "state": "WA", "country": "US",
        "latitude": 46.9336, "longitude": -121.4748,
        "summit_elevation_ft": 7002, "vertical_drop_ft": 3100,
        "website": "https://www.crystalmountainresort.com", "timezone": "America/Los_Angeles",
        "liftie_id": "crystal-mountain", "onthesnow_slug": "washington/crystal-mountain-resort",
    },
    {
        "id": "revelstoke", "name": "Revelstoke Mountain", "pass_type": "ikon",
        "region": "British Columbia", "state": "BC", "country": "CA",
        "latitude": 51.0592, "longitude": -118.1773,
        "summit_elevation_ft": 7300, "vertical_drop_ft": 5620,
        "website": "https://www.revelstokemountainresort.com", "timezone": "America/Vancouver",
        "liftie_id": "revelstoke", "onthesnow_slug": "british-columbia/revelstoke-mountain-resort",
    },
    {
        "id": "tremblant", "name": "Mont-Tremblant", "pass_type": "ikon",
        "region": "Quebec", "state": "QC", "country": "CA",
        "latitude": 46.2154, "longitude": -74.5840,
        "summit_elevation_ft": 3001, "vertical_drop_ft": 2116,
        "website": "https://www.tremblant.ca", "timezone": "America/Toronto",
        "liftie_id": "tremblant", "onthesnow_slug": "quebec/mont-tremblant",
    },
    {
        "id": "deer-valley", "name": "Deer Valley", "pass_type": "ikon",
        "region": "Utah", "state": "UT", "country": "US",
        "latitude": 40.6374, "longitude": -111.4784,
        "summit_elevation_ft": 9570, "vertical_drop_ft": 3000,
        "website": "https://www.deervalley.com", "timezone": "America/Denver",
        "liftie_id": "deer-valley", "onthesnow_slug": "utah/deer-valley-resort",
    },
    {
        "id": "solitude", "name": "Solitude Mountain", "pass_type": "ikon",
        "region": "Utah", "state": "UT", "country": "US",
        "latitude": 40.6199, "longitude": -111.5920,
        "summit_elevation_ft": 10035, "vertical_drop_ft": 2047,
        "website": "https://www.skisolitude.com", "timezone": "America/Denver",
        "liftie_id": "solitude", "onthesnow_slug": "utah/solitude-mountain-resort",
    },
    {
        "id": "blue-mountain", "name": "Blue Mountain", "pass_type": "ikon",
        "region": "Ontario", "state": "ON", "country": "CA",
        "latitude": 44.5018, "longitude": -80.3172,
        "summit_elevation_ft": 1400, "vertical_drop_ft": 720,
        "website": "https://www.bluemountain.ca", "timezone": "America/Toronto",
        "liftie_id": "blue-mountain", "onthesnow_slug": "ontario/blue-mountain",
    },
    {
        "id": "schweitzer", "name": "Schweitzer Mountain", "pass_type": "ikon",
        "region": "Pacific Northwest", "state": "ID", "country": "US",
        "latitude": 48.3586, "longitude": -116.6224,
        "summit_elevation_ft": 6393, "vertical_drop_ft": 2400,
        "website": "https://www.schweitzer.com", "timezone": "America/Los_Angeles",
        "liftie_id": "schweitzer", "onthesnow_slug": "idaho/schweitzer-mountain-resort",
    },
]


def seed_resorts(db: Session) -> None:
    """Insert all resorts if they don't already exist (idempotent)."""
    for data in RESORTS:
        existing = db.query(Resort).filter_by(id=data["id"]).first()
        if not existing:
            db.add(Resort(**data))
    db.commit()
