"""initial schema

Revision ID: ac476b324a60
Revises: 
Create Date: 2026-03-17 19:08:08.942575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac476b324a60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resort_id', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hourly_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resort_id', 'day_of_week')
    )
    op.create_index(op.f('ix_crowd_data_resort_id'), 'crowd_data', ['resort_id'], unique=False)
    op.create_table('lift_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resort_id', sa.String(), nullable=False),
    sa.Column('lift_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lift_status_resort_id'), 'lift_status', ['resort_id'], unique=False)
    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resort_id', sa.String(), nullable=False),
    sa.Column('lot_name', sa.String(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('capacity_pct', sa.Integer(), nullable=True),
    sa.Column('distance_ft', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('directions_url', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_lots_resort_id'), 'parking_lots', ['resort_id'], unique=False)
    op.create_table('resorts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pass_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('summit_elevation_ft', sa.Integer(), nullable=True),
    sa.Column('vertical_drop_ft', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('liftie_id', sa.String(), nullable=False),
    sa.Column('onthesnow_slug', sa.String(), nullable=False),
    sa.Column('noaa_grid_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraper_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scraper_name', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('skip_until_run', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_health_scraper_name'), 'scraper_health', ['scraper_name'], unique=False)
    op.create_table('snow_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resort_id', sa.String(), nullable=False),
    sa.Column('base_in', sa.Float(), nullable=True),
    sa.Column('new_24h_in', sa.Float(), nullable=True),
    sa.Column('new_48h_in', sa.Float(), nullable=True),
    sa.Column('new_7d_in', sa.Float(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('trails_open', sa.Integer(), nullable=True),
    sa.Column('trails_total', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snow_conditions_resort_id'), 'snow_conditions', ['resort_id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resort_id', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.String(), nullable=False),
    sa.Column('high_f', sa.Float(), nullable=True),
    sa.Column('low_f', sa.Float(), nullable=True),
    sa.Column('precip_pct', sa.Integer(), nullable=True),
    sa.Column('snow_in_forecast', sa.Boolean(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_resort_id'), 'weather_forecasts', ['resort_id'], unique=False)
    op.create_table('webcams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resort_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('cam_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webcams_resort_id'), 'webcams', ['resort_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webcams_resort_id'), table_name='webcams')
    op.drop_table('webcams')
    op.drop_index(op.f('ix_weather_forecasts_resort_id'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index(op.f('ix_snow_conditions_resort_id'), table_name='snow_conditions')
    op.drop_table('snow_conditions')
    op.drop_index(op.f('ix_scraper_health_scraper_name'), table_name='scraper_health')
    op.drop_table('scraper_health')
    op.drop_table('resorts')
    op.drop_index(op.f('ix_parking_lots_resort_id'), table_name='parking_lots')
    op.drop_table('parking_lots')
    op.drop_index(op.f('ix_lift_status_resort_id'), table_name='lift_status')
    op.drop_table('lift_status')
    op.drop_index(op.f('ix_crowd_data_resort_id'), table_name='crowd_data')
    op.drop_table('crowd_data')
    # ### end Alembic commands ###
